appConfig:
  language: de
  theme: vaporware
  auth:
    users:
      - user: TestUser
        hash: 2EB4C124891BC1F82E6B2CE294934139F21450CBF67288E029D6F4F6D241A0E7
        type: normal
      - user: PJoK
        hash: C43E3309600CDF255AFF2D28A1A14A1C31C75E7B04E8E05293D73641AAE33FF0
        type: admin
      - user: ingressy
        hash: C4B4ECAF876E6EE9F431D5F2662FE738BFA2C986869AF1B09BE9C8EC8D6F609C
        type: admin
      - user: Lecuve
        hash: 554CB2F43D2BDF9AAB8A3EFCAB43BEDBC9C3B92DC7A6996B3AC4A0633AAD5737
        type: admin
      - user: Jusch
        hash: EF5BC17A57DEFBBA74C0BF786478C0A70B9D4558F8B411C3834F83930EF95A41
        type: admin
    enableGuestAccess: false
    enableOidc: false
    enableHeaderAuth: false
    headerAuth:
      userHeader: REMOTE_USER
      proxyWhitelist: []
    enableKeycloak: false
  layout: auto
  iconSize: medium
  startingView: default
  defaultOpeningMethod: newtab
  statusCheck: false
  statusCheckInterval: 0
  faviconApi: allesedv
  routingMode: history
  enableMultiTasking: false
  widgetsAlwaysUseProxy: false
  webSearch:
    disableWebSearch: false
    searchEngine: duckduckgo
    openingMethod: newtab
    searchBangs: {}
  enableFontAwesome: true
  enableMaterialDesignIcons: false
  hideComponents:
    hideHeading: false
    hideNav: false
    hideSearch: false
    hideSettings: false
    hideFooter: false
  showSplashScreen: false
  preventWriteToDisk: false
  preventLocalSave: false
  disableConfiguration: false
  disableConfigurationForNonAdmin: true
  allowConfigEdit: true
  enableServiceWorker: false
  disableContextMenu: false
  disableUpdateChecks: false
  disableSmartSort: false
  enableErrorReporting: false
pageInfo:
  title: DoorSign Dashboard
  navLinks: []
sections:
  - name: LinkTree
    icon: far fa-rocket
    displayData:
      showForUsers:
        - ingressy
        - PJoK
        - TestUser
        - Lecuve
      sortBy: most-used
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: true
    items:
      - title: GitHub
        description: DoorSign GitHub Main
        icon: fab fa-github
        url: https://github.com/tbz-nerd-ag/e-paper-main
        id: 0_798_github
      - title: Trello
        description: Trello Link
        icon: https://cdn.worldvectorlogo.com/logos/trello.svg
        url: https://trello.com/b/BFe7LYSv/e-paper
        target: newtab
        id: 1_798_trello
      - title: Discord
        description: AG Discord Server
        icon: >-
          https://cdn.prod.website-files.com/6257adef93867e50d84d30e2/636e0a69f118df70ad7828d4_icon_clyde_blurple_RGB.svg
        url: https://discord.gg/jh49n4hRMr
        target: newtab
        id: 2_798_discord
pages:
  - name: display-stats
    path: displayStat.yml
    displayData:
      hideForGuests: false